ATTACK_ITERATIONS_COUNT: 10
KEY_GENERATION:
  E_MAX_LENGTH: 5
  E_OPTIONS_MAX_COUNT: 5
  FIRST_SAMPLE_MAX_SIZE: 2
  KEY_LENGTH: 16  
  MIDDLE_SAMPLE_MAX_SIZE: 3
  PRIME_MIN_LENGTH: 2
  THIRD_SAMPLE_MAX_SIZE: 2
STATS_ITERATIONS_COUNT: 100
